development:
  adapter: postgresql
  encoding: unicode
  database: coming_soon_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: coming_soon_test
  pool: 5
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: coming_soon_production
  pool: 5
  host: localhost

